version: 2

updates:
  # Main application dependencies (v1/)
  - package-ecosystem: "npm"
    directory: "/v1"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "@battel-maintainers"
    assignees:
      - "@battel-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    versioning-strategy: "increase-if-necessary"
    target-branch: "develop"

  # Root level dependencies (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@battel-maintainers"
    assignees:
      - "@battel-maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    versioning-strategy: "increase-if-necessary"
    target-branch: "develop"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@battel-maintainers"
    assignees:
      - "@battel-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
      - "ci/cd"
    target-branch: "develop" 